Repository paypal/paypal-messaging-components, pull requests merged in 2021-11, with the labels that each got.

#601 feat: DE Pi30 modal
  modals/DE/gpl.json
  modals/DE/pi30.json
  src/components/modal/content/DE-GPL/parts/Content.jsx
  src/components/modal/content/DE-GPL/parts/ContentWrapper.jsx
  src/components/modal/content/DE-GPL/parts/GPL.jsx
  src/components/modal/content/DE-GPL/parts/Pi30.jsx
  src/components/modal/content/DE-GPL/parts/ProductButton.jsx
  src/components/modal/content/DE-GPL/parts/ProductList.jsx
  src/components/modal/content/DE-GPL/styles/content.scss
  src/components/modal/content/DE-GPL/styles/header.scss
  src/components/modal/content/DE-GPL/styles/main.scss
  src/components/modal/parts/Icon.jsx
  src/controllers/modal/interface.js
  src/utils/miscellaneous.js
  utils/devServerProxy/proxy.js
Labels: testing complete, downstream dependency, approved

#661 feat: DE Pi30 modal instrumentation [snapshots]
  demo/helpers/accounts.js
  src/components/modal/content/DE-GPL/parts/Content.jsx
  src/components/modal/content/DE-GPL/parts/ProductList.jsx
  tests/functional/spec/DE/accounts.js
  tests/functional/spec/DE/modal/base.test.js
  tests/functional/spec/DE/modal/de_modalTestDefs.js
  tests/functional/spec/utils/modalSnapshot.js
  tests/functional/spec/utils/selectors.js
  utils/devServerProxy/proxy.js
Labels: testing complete, approved

#659 feat: pay in 4 modal view
  content/modals/US/short_term.json
  content/offers/US/short_term.json
  src/components/modal/v2/parts/ContentWrapper.jsx
  src/components/modal/v2/parts/Donut.jsx
  src/components/modal/v2/parts/Header.jsx
  src/components/modal/v2/parts/Icon.jsx
  src/components/modal/v2/parts/views/ShortTerm/Content.jsx
  src/components/modal/v2/parts/views/ShortTerm/styles.scss
  src/components/modal/v2/parts/views/index.js
  src/components/modal/v2/styles/components/_donut.scss
Labels: testing complete, approved

#638 feat: add ni universal modal
  content/modals/US/ni_v2.json
  content/offers/US/ni.json
  demo/standalone-modal.html
  src/components/modal/v2/lib/hooks/applyNow.js
  src/components/modal/v2/lib/hooks/index.js
  src/components/modal/v2/parts/ContentWrapper.jsx
  src/components/modal/v2/parts/views/NI/Content.jsx
  src/components/modal/v2/parts/views/NI/styles.scss
  src/components/modal/v2/parts/views/index.js
  src/components/modal/v2/styles/globals/_colors.scss
  utils/devServerProxy/config/devAccountsV2.config.js
Labels: DO NOT MERGE
