Repository paypal/paypal-messaging-components, pull requests merged in 2021-08, with the labels that each got.

#573 fix: remove collapsed elements from overflow calculation
  demo/snapshot/overflow/below-the-fold.html
  demo/snapshot/overflow/fixed.html
  demo/snapshot/overflow/html-body-100.html
  demo/snapshot/overflow/standard.html
  src/utils/elements.js
  src/utils/observers.js
  tests/functional/spec/non-snapshot-tests/overflow.test.js
Labels: approved, testing complete

#554 fix: ie11 loading issue
  src/utils/performance.js
Labels: approved, testing complete

#537 refactor: remove Preact from messages
  globals.js
  src/components/message/Message.js
  src/components/message/Message.jsx
  src/components/message/index.js
  src/components/message/lib/index.js
  src/utils/sdk.js
  src/zoid/message/component.js
  src/zoid/modal/component.js
  tests/unit/spec/src/components/message/Message.test.js
  tests/unit/utils/xPropsMock.js
  utils/devServerProxy/proxy.js
  webpack.config.dev.js
  webpack.config.js
Labels: approved, downstream dependency, testing complete

#540 feat: default PayPal fonts to off [snapshots]
  server/message/index.jsx
  server/message/parts/Styles.jsx
  server/message/styles/common.css
  server/message/styles/flex/base.css
  server/message/styles/fonts.css
  tests/unit/spec/server/message/index.test.js
  tests/unit/spec/src/components/message/parts/Styles.test.js
Labels: dirty screenshots, testing complete

#566 refactor: update GPL US modal disclosure
  modals/US/gpl.json
Labels: testing complete, approved

#568 refactor: remove container size fallback re-render functionality
  server/locale/AU/index.js
  server/locale/AU/validOptions.js
  server/locale/DE/GPL/validOptions.js
  server/locale/DE/Ratenzahlung/validOptions.js
  server/locale/FR/index.js
  server/locale/FR/validOptions.js
  server/locale/GB/index.js
  server/locale/GB/validOptions.js
  server/locale/US/GPL/index.js
  server/locale/US/GPL/validOptions.js
  server/locale/US/PPC/index.js
  server/locale/US/PPC/validOptions.js
  server/locale/index.js
  server/message/index.jsx
  src/utils/observers.js
Labels: testing complete, approved

#567 refactor: remove modal prefetch [snapshots]
  demo/snapshot/modal-standalone.html
  package.json
  server/locale/DE/GPL/styles/flex/ratio--1x1.css
  server/locale/DE/GPL/styles/flex/ratio--8x1.css
  src/components/modal/content/US-EZP/parts/ContentWrapper.jsx
  src/components/modal/lib/providers/transition.js
  src/components/modal/parts/Container.jsx
  src/components/modal/styles/modal-frame.scss
  src/controllers/modal/interface.js
  src/controllers/modal/setup.js
  src/utils/observers.js
  src/zoid/message/component.js
  src/zoid/modal/component.js
  src/zoid/modal/containerTemplate.jsx
  src/zoid/modal/prerenderTemplate.jsx
  tests/functional/spec/non-snapshot-tests/payload.test.js
  tests/functional/spec/utils/initializeModal.js
  tests/functional/spec/utils/modalSnapshot.js
  tests/functional/spec/utils/setupTestPage.js
  tests/unit/spec/src/components/modal/lib/providers/transition.test.js
  tests/unit/spec/src/components/modal/parts/Container.test.js
  tests/unit/spec/src/controllers/modal/interface.test.js
  tests/unit/spec/src/utils/miscellaneous.test.js
Labels: dirty screenshots, testing complete, approved

#584 ci: fix standalone modal test page [snapshots]
  demo/snapshot/modal-standalone.html
Labels: approved

#577 fix: address DE GPL style bugs [snapshots]
  server/locale/DE/GPL/styles/flex/base.css
  server/locale/DE/GPL/styles/flex/ratio--6x1.css
  server/message/parts/MutatedText.jsx
  src/components/modal/content/DE-GPL/parts/Calculator.jsx
  src/components/modal/content/DE-GPL/styles/termsTable.scss
Labels: dirty screenshots, testing complete, approved

#583 refactor: add ignoreCache option to modal
  src/components/message/Message.js
  src/components/modal/lib/hooks/calculator.js
  src/components/modal/lib/utils.js
  src/components/modal/parts/Container.jsx
  src/controllers/message/interface.js
  src/controllers/modal/interface.js
  src/zoid/modal/component.js
Labels: testing complete, approved

#586 ci: improve generated release notes
  .releaserc.js
  package.json
Labels: approved

#591 refactor: omit pp_debug when missing
  src/zoid/message/component.js
  src/zoid/modal/component.js
Labels: testing complete, approved

#594 fix: DE GPL flex banner styles [snapshots]
  server/locale/DE/GPL/mutations/gpl_eqz-non-de.js
  server/locale/DE/GPL/mutations/gpl_eqz.js
  server/locale/DE/GPL/mutations/gpl_gtz-non-de.js
  server/locale/DE/GPL/mutations/gpl_gtz.js
  server/locale/DE/GPL/mutations/gplq_eqz-non-de.js
  server/locale/DE/GPL/mutations/gplq_eqz.js
  server/locale/DE/GPL/mutations/gplq_gtz-non-de.js
  server/locale/DE/GPL/mutations/gplq_gtz.js
  server/locale/DE/GPL/styles/flex/base.css
  server/locale/DE/GPL/styles/flex/ratio--1x1.css
  server/locale/DE/GPL/styles/flex/ratio--1x4.css
  server/locale/DE/GPL/styles/flex/ratio--20x1.css
  server/locale/DE/GPL/styles/flex/ratio--6x1.css
  server/locale/DE/GPL/styles/flex/ratio--8x1.css
Labels: dirty screenshots, testing complete, approved

#598 fix: remove currency and buyerCountry strictness
  locales.js
  package.json
  src/components/message/Message.js
  src/zoid/message/validation.js
  tests/unit/spec/src/zoid/message/validation.test.js
Labels: testing complete, approved

#600 fix: use unformated APR for DE GPL disclosure check [snapshots]
  server/render.jsx
  src/components/modal/content/DE-GPL/parts/GPL.jsx
Labels: testing complete, approved
