Repository paypal/paypal-messaging-components, pull requests merged in 2021-05, with the labels that each got.

#504 refactor: use dynamic min and max for GPLNQ range message [snapshots]
  banners/US/gplnq_range.json
  server/locale/US/GPL/mutations/gplnq_range.js
  server/message/parts/MutatedText.jsx
Labels: approved, ready to merge

#508 fix: improve automatic message rendering
  src/utils/observers.js
  tests/unit/spec/src/controllers/message/setup.test.js
Labels: ready to merge

#501 feat: allow messages to render while offscreen
  src/controllers/message/destroy.js
  src/utils/elements.js
  src/utils/observers.js
  src/utils/stats.js
  tests/unit/spec/src/utils/stats.test.js
Labels: ready to merge

#481 feat: add text align to FR
  server/locale/FR/styles/text/index.js
  server/locale/FR/styles/text/logo--right.css
  server/locale/FR/styles/text/text--center-logo--alternative.css
  server/locale/FR/styles/text/text--center-logo--primary.css
  server/locale/FR/styles/text/text--center.css
  server/locale/FR/styles/text/text--right-logo--alternative.css
  server/locale/FR/styles/text/text--right-logo--inline.css
  server/locale/FR/styles/text/text--right-logo--primary.css
  server/locale/FR/styles/text/text--right.css
  server/locale/FR/validOptions.js
  tests/functional/spec/FR/banner/text.test.js
Labels: ready to merge

#480 feat: add text align to GB [snapshots]
  server/locale/GB/styles/text/index.js
  server/locale/GB/styles/text/text--center-logo--alternative.css
  server/locale/GB/styles/text/text--center-logo--primary.css
  server/locale/GB/styles/text/text--center.css
  server/locale/GB/styles/text/text--right-logo--alternative.css
  server/locale/GB/styles/text/text--right-logo--inline.css
  server/locale/GB/styles/text/text--right-logo--primary.css
  server/locale/GB/styles/text/text--right.css
  server/locale/GB/validOptions.js
  tests/functional/spec/GB/banner/text.test.js
Labels: ready to merge

#471 refactor: instrument performance metrics
  jest.config.js
  src/controllers/message/interface.js
  src/controllers/message/setup.js
  src/controllers/modal/interface.js
  src/interface/experiment.js
  src/interface/index.js
  src/utils/events.js
  src/utils/index.js
  src/utils/logger.js
  src/utils/performance.js
  src/utils/sdk.js
  src/utils/stats.js
  src/zoid/modal/component.js
  tests/.eslintrc
  tests/customMatchers.js
  tests/functional/jest.noSnapshots.config.js
  tests/functional/spec/non-snapshot-tests/payload.test.js
  tests/unit/spec/src/utils/performance.test.js
  tests/unit/spec/src/utils/stats.test.js
Labels: downstream dependency, ready to merge
