Repository paypal/paypal-messaging-components, pull requests merged in 2021-04, with the labels that each got.

#445 refactor: synchronizing local message source with content repo
  banners/DE/inst_any_eqz.json
  banners/DE/inst_any_gtz.json
  banners/DE/palaq_any_eqz.json
  banners/DE/palaq_any_gtz.json
  banners/FR/gpl.json
  banners/FR/gplq.json
  banners/GB/pl.json
  banners/GB/plq.json
  banners/US/ezp_any_eqz.json
  banners/US/ezp_any_gtz.json
  banners/US/gpl.json
  banners/US/gplnq.json
  banners/US/gplnq_range.json
  banners/US/gplq.json
  banners/US/ni.json
  banners/US/ni_non-us.json
  banners/US/niq.json
  banners/US/niq_non-us.json
  banners/US/pala_multi_eqz.json
  banners/US/pala_multi_gtz.json
  banners/US/pala_single_eqz.json
  banners/US/pala_single_gtz.json
Labels: DO NOT MERGE

#462 feat: AU GPL text messages
  .travis.yml
  banners/AU/gpl.json
  banners/AU/gplq.json
  demo/helpers/accounts.js
  docs/message-offer-types.md
  locales.js
  server/locale/AU/index.js
  server/locale/AU/mutations/gpl.js
  server/locale/AU/mutations/gplq.js
  server/locale/AU/mutations/index.js
  server/locale/AU/styles/index.js
  server/locale/AU/styles/text/base.css
  server/locale/AU/styles/text/index.js
  server/locale/AU/styles/text/logo--alternative.css
  server/locale/AU/styles/text/logo--inline.css
  server/locale/AU/styles/text/logo--none.css
  server/locale/AU/styles/text/logo--primary.css
  server/locale/AU/styles/text/logo--right.css
  server/locale/AU/styles/text/logo--top.css
  server/locale/AU/styles/text/text--center-logo--alternative.css
  server/locale/AU/styles/text/text--center-logo--primary.css
  server/locale/AU/styles/text/text--center.css
  server/locale/AU/styles/text/text--grayscale.css
  server/locale/AU/styles/text/text--monochrome.css
  server/locale/AU/styles/text/text--right-logo--alternative.css
  server/locale/AU/styles/text/text--right-logo--inline.css
  server/locale/AU/styles/text/text--right-logo--primary.css
  server/locale/AU/styles/text/text--right.css
  server/locale/AU/styles/text/text--white.css
  server/locale/AU/validOptions.js
  server/locale/index.js
  server/message/mediaQueries.js
  tests/functional/spec/AU/accounts.js
  tests/functional/spec/AU/banner/text.test.js
  tests/unit/spec/server/locale/index.test.js
  utils/devServerProxy/miscellaneous.js
  utils/devServerProxy/proxy.js
Labels: approved, into PR

#469 fix: allow EZP messages to fit in smaller spaces
  .travis.yml
  server/locale/US/PPC/mutations/ezp_any_eqz.js
  server/locale/US/PPC/mutations/ezp_any_gtz.js
  server/locale/US/PPC/mutations/pala_multi_eqz.js
  server/locale/US/PPC/mutations/pala_single_eqz.js
  server/locale/US/PPC/mutations/pala_single_gtz.js
Labels: ready to merge

#465 refactor: FR GPL sans frais
  .travis.yml
  banners/FR/gpl.json
  banners/FR/gplq.json
  modals/FR/gpl.json
  server/locale/FR/mutations/gpl.js
  server/locale/FR/mutations/gplq.js
  server/locale/FR/styles/flex/ratio--1x1.css
  server/locale/FR/styles/flex/ratio--8x1.css
Labels: approved, ready to merge

#468 feat: AU GPL flex messages
  .github/workflows/main.yml
  server/locale/AU/mutations/gpl.js
  server/locale/AU/mutations/gplq.js
  server/locale/AU/styles/flex/base.css
  server/locale/AU/styles/flex/color--black.css
  server/locale/AU/styles/flex/color--blue.css
  server/locale/AU/styles/flex/color--gray.css
  server/locale/AU/styles/flex/color--grayscale.css
  server/locale/AU/styles/flex/color--monochrome.css
  server/locale/AU/styles/flex/color--white-no-border.css
  server/locale/AU/styles/flex/color--white.css
  server/locale/AU/styles/flex/index.js
  server/locale/AU/styles/flex/ratio--1x1.css
  server/locale/AU/styles/flex/ratio--1x4.css
  server/locale/AU/styles/flex/ratio--20x1.css
  server/locale/AU/styles/flex/ratio--6x1.css
  server/locale/AU/styles/flex/ratio--8x1.css
  server/locale/AU/styles/index.js
  server/locale/AU/validOptions.js
  tests/functional/spec/AU/banner/flex.test.js
Labels: approved, into PR

#484 feat: AU GPL modal
  demo/snapshot/modal-test.html
  modals/AU/gpl.json
  src/components/modal/content/AU/index.js
  src/components/modal/content/AU/parts/ContentWrapper.jsx
  src/components/modal/content/AU/parts/GPL.jsx
  src/components/modal/content/AU/styles/content.scss
  src/components/modal/content/AU/styles/header.scss
  src/components/modal/content/AU/styles/index.scss
  src/components/modal/content/AU/styles/main.scss
  src/components/modal/content/AU/styles/mixins.scss
  src/components/modal/parts/Header.jsx
  tests/functional/spec/AU/modal/au_modalTestDefs.js
  tests/functional/spec/AU/modal/text.test.js
  tests/functional/spec/utils/modalSnapshot.js
Labels: into PR

#470 refactor: sending session and device unique identifiers to tracking endpoint (DTCRCMERC-927)
  src/utils/logger.js
  src/utils/sdk.js
  src/zoid/message/component.js
  src/zoid/modal/component.js
Labels: approved

#491 feat: DE GPL cross-border messages
  banners/DE/gpl_eqz-non-de.json
  banners/DE/gpl_gtz-non-de.json
  banners/DE/gplq_eqz-non-de.json
  banners/DE/gplq_gtz-non-de.json
  demo/helpers/accounts.js
  docs/message-offer-types.md
  server/locale/DE/GPL/mutations/gpl_eqz-non-de.js
  server/locale/DE/GPL/mutations/gpl_gtz-non-de.js
  server/locale/DE/GPL/mutations/gplq_eqz-non-de.js
  server/locale/DE/GPL/mutations/gplq_gtz-non-de.js
  server/locale/DE/GPL/mutations/index.js
  server/locale/DE/GPL/mutations/mediaQueries.js
  server/locale/DE/GPL/styles/flex/base.css
  server/locale/DE/GPL/styles/flex/ratio--20x1.css
  server/locale/DE/index.js
  tests/functional/spec/DE/accounts.js
  tests/unit/spec/server/locale/index.test.js
  utils/devServerProxy/proxy.js
Labels: into PR
