Repository paypal/paypal-messaging-components, pull requests merged in 2022-02, with the labels that each got.

#697 feat: add additional instrumentation to Long Term and Product List views
  src/components/modal/v2/parts/ProductListLink.jsx
  src/components/modal/v2/parts/Tile.jsx
  src/components/modal/v2/parts/views/LongTerm/Content.jsx
Labels: testing complete, approved

#690 feat: expand modal for api iframes
  README.md
  package.json
  src/components/modal/v2/parts/BodyContent.jsx
  src/components/modal/v2/parts/Container.jsx
  src/components/modal/v2/parts/views/NI/styles.scss
  src/components/modal/v2/styles/components/_body-content.scss
  src/components/modal/v2/styles/components/_header.scss
  src/components/modal/v2/styles/globals/_mixins.scss
  src/components/modal/v2/styles/globals/_variables.scss
Labels: testing complete, approved

#684 feat: channel and integration identifer logging
  src/library/controllers/modal/interface.js
  src/library/zoid/message/component.js
  src/library/zoid/modal/component.js
  src/utils/miscellaneous.js
Labels: testing complete, approved

#707 feat: gpl it text
  server/locale/IT/mutations/short_term_no_amount.js
  server/locale/IT/mutations/short_term_nq.js
  server/locale/IT/mutations/short_term_q.js
  server/locale/IT/styles/text/base.css
  server/locale/IT/styles/text/index.js
  server/locale/IT/styles/text/logo--alternative.css
  server/locale/IT/styles/text/logo--inline.css
  server/locale/IT/styles/text/logo--none.css
  server/locale/IT/styles/text/logo--primary.css
  server/locale/IT/styles/text/logo--right.css
  server/locale/IT/styles/text/logo--top.css
  server/locale/IT/styles/text/text--center-logo--alternative.css
  server/locale/IT/styles/text/text--center-logo--primary.css
  server/locale/IT/styles/text/text--center.css
  server/locale/IT/styles/text/text--grayscale.css
  server/locale/IT/styles/text/text--monochrome.css
  server/locale/IT/styles/text/text--right-logo--alternative.css
  server/locale/IT/styles/text/text--right-logo--inline.css
  server/locale/IT/styles/text/text--right-logo--primary.css
  server/locale/IT/styles/text/text--right.css
  server/locale/IT/styles/text/text--white.css
Labels: approved, snapshots

#722 feat: IT Flex Banners
  demo/helpers/accounts.js
  server/locale/IT/mutations/short_term_no_amount.js
  server/locale/IT/mutations/short_term_nq.js
  server/locale/IT/mutations/short_term_q.js
  server/locale/IT/styles/flex/base.css
  server/locale/IT/styles/flex/color--black.css
  server/locale/IT/styles/flex/color--blue.css
  server/locale/IT/styles/flex/color--gray.css
  server/locale/IT/styles/flex/color--grayscale.css
  server/locale/IT/styles/flex/color--monochrome.css
  server/locale/IT/styles/flex/color--white-no-border.css
  server/locale/IT/styles/flex/color--white.css
  server/locale/IT/styles/flex/index.js
  server/locale/IT/styles/flex/ratio--1x1.css
  server/locale/IT/styles/flex/ratio--1x4.css
  server/locale/IT/styles/flex/ratio--20x1.css
  server/locale/IT/styles/flex/ratio--6x1.css
  server/locale/IT/styles/flex/ratio--8x1.css
  server/locale/IT/validOptions.js
  server/locale/index.js
  utils/devServerProxy/proxy.js
Labels: snapshots

#728 fix: prevent false show events
  src/components/modal/content/DE-GPL/parts/Content.jsx
  src/components/modal/lib/providers/transition.js
  src/components/modal/v2/lib/hooks/applyNow.js
  src/components/modal/v2/lib/providers/transition.js
  src/components/modal/v2/parts/Container.jsx
  src/components/modal/v2/parts/InlineLinks.jsx
  src/components/modal/v2/parts/Instructions.jsx
  src/components/modal/v2/parts/Modal.jsx
  src/components/modal/v2/parts/views/NI/styles.scss
  src/components/modal/v2/styles/components/_body-content.scss
  src/components/modal/v2/styles/components/_header.scss
  src/components/modal/v2/styles/components/_instructions.scss
  src/components/modal/v2/styles/components/_modal-frame.scss
  src/components/modal/v2/styles/globals/_common.scss
  src/components/modal/v2/styles/index.scss
  src/library/zoid/modal/containerTemplate.jsx
  tests/functional/snapshots/DE/DEV0DEPI30GPL/modal/flex,wid-411,amt-undef_esc-key-modal-close-snap.png
  tests/functional/snapshots/DE/DEV0DEPI30GPL/modal/flex,wid-411,amt-undef_ezp-x-button-closes-modal-snap.png
  tests/functional/snapshots/DE/DEV0DEPI30GPL/modal/flex,wid-411,amt-undef_reopen-and-close-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/flex,wid-411,amt-undef_apply-now-button-to-credit-application-login-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/flex,wid-411,amt-undef_esc-key-modal-close-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/flex,wid-411,amt-undef_ni-content-in-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/flex,wid-411,amt-undef_ni-x-button-closes-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/flex,wid-411,amt-undef_reopen-and-close-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/flex,wid-411,amt-undef_see-terms-page-on-modal-hyperlink-click-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-1920,amt-undef_apply-now-button-to-credit-application-login-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-1920,amt-undef_ni-content-in-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-1920,amt-undef_see-terms-page-on-modal-hyperlink-click-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-411,amt-undef_apply-now-button-to-credit-application-login-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-411,amt-undef_esc-key-modal-close-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-411,amt-undef_ni-content-in-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-411,amt-undef_ni-x-button-closes-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-411,amt-undef_reopen-and-close-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/standalone-modal,wid-411,amt-undef_see-terms-page-on-modal-hyperlink-click-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-1920,amt-undef_apply-now-button-to-credit-application-login-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-1920,amt-undef_ni-content-in-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-1920,amt-undef_see-terms-page-on-modal-hyperlink-click-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-411,amt-undef_apply-now-button-to-credit-application-login-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-411,amt-undef_esc-key-modal-close-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-411,amt-undef_ni-content-in-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-411,amt-undef_ni-x-button-closes-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-411,amt-undef_reopen-and-close-modal-snap.png
  tests/functional/snapshots/US/DEV00000000NI/modal/text,wid-411,amt-undef_see-terms-page-on-modal-hyperlink-click-snap.png
Labels: testing complete, approved

#747 fix: updated replace for logo none and inline
  src/server/locale/DE/Pi30/mutations/pi30q.js
  tests/functional/snapshots/DE/DEV000DEPI30Q/text/logo.type-inline-1000-snap.png
  tests/functional/snapshots/DE/DEV000DEPI30Q/text/logo.type-inline_text.color-grayscale-1000-snap.png
  tests/functional/snapshots/DE/DEV000DEPI30Q/text/logo.type-inline_text.color-monochrome-1000-snap.png
  tests/functional/snapshots/DE/DEV000DEPI30Q/text/logo.type-inline_text.color-white-1000-snap.png
  tests/functional/snapshots/DE/DEV000DEPI30Q/text/logo.type-none-1000-snap.png
  tests/functional/snapshots/DE/DEV000DEPI30Q/text/logo.type-none_text.color-grayscale-1000-snap.png
  tests/functional/snapshots/DE/DEV000DEPI30Q/text/logo.type-none_text.color-monochrome-1000-snap.png
  tests/functional/snapshots/DE/DEV000DEPI30Q/text/logo.type-none_text.color-white-1000-snap.png
Labels: testing complete, approved

#717 refactor: update performance entry search (DTCRCGEMI-194)
  src/library/zoid/message/component.js
  src/utils/performance.js
  tests/unit/spec/src/components/message/Message.test.js
  tests/unit/spec/src/utils/stats.test.js
Labels: testing complete, approved

#744 fix: remove touchmove events to prevent scroll miscalculations
  src/components/modal/v2/lib/providers/scroll.js
Labels: testing complete, approved

#745 fix: universal modal donut font sizing and spacing
  src/components/modal/v2/parts/views/ShortTerm/styles.scss
  src/components/modal/v2/styles/components/_donut.scss
Labels: testing complete, approved

#748 fix: add missing NI offerType map values
  src/utils/miscellaneous.js
Labels: testing complete, approved

#746 fix: product list link render condition
  src/components/modal/v2/parts/views/LongTerm/Content.jsx
  src/components/modal/v2/parts/views/NI/Content.jsx
  src/components/modal/v2/parts/views/ShortTerm/Content.jsx
Labels: testing complete, approved

#701 fix: accessibility issues including reverse tabbing and nav link focus
  src/components/modal/content/US/parts/Content.jsx
  src/components/modal/content/US/parts/NI.jsx
  src/components/modal/content/US/styles/content.scss
  src/components/modal/lib/utils.js
  src/components/modal/parts/Header.jsx
  src/components/modal/styles/header.scss
  src/library/zoid/message/component.js
Labels: testing complete, approved

#739 fix: ensure callback functions work
  demo/blank.html
  src/library/controllers/message/interface.js
  tests/functional/spec/non-snapshot-tests/onEvents.test.js
  tests/functional/spec/utils/selectors.js
  tests/unit/spec/src/controllers/message/interface.test.js
  tests/unit/spec/src/controllers/modal/interface.test.js
Labels: bug, testing complete, approved

#729 fix: buyerCountry updates modal
  src/library/controllers/modal/interface.js
Labels: testing complete, approved
