Repository paypal/paypal-messaging-components, pull requests merged in 2023-12, with the labels that each got.

#1024 feat: update US Pi4 PL2GO legal disclosure content
  content/modals/US/PL2GO/pl2go_short_term.json
Labels: testing complete, approved

#1015 feat: Add blur to Calculator input
  src/components/modal/v2/parts/Calculator.jsx
Labels: testing complete, approved

#1027 feat: Update PL HUB learn more modals to use QL style
  content/modals/AU/short_term.json
  content/modals/ES/short_term_en.json
  content/modals/FR/short_term_en.json
  content/modals/GB/short_term.json
  content/modals/US/PLHub/plhub_long_term.json
  content/modals/US/PLHub/plhub_short_term.json
  src/components/modal/v2/parts/BodyContent.jsx
  src/components/modal/v2/parts/Calculator.jsx
  src/components/modal/v2/parts/Donut.jsx
  src/components/modal/v2/parts/Header.jsx
  src/components/modal/v2/parts/Instructions.jsx
  src/components/modal/v2/parts/OfferCard.jsx
  src/components/modal/v2/parts/TermsTable.jsx
  src/components/modal/v2/parts/views/LongTerm/Content.jsx
  src/components/modal/v2/parts/views/ShortTerm/Content.jsx
  src/components/modal/v2/styles/components/_calculator.scss
  src/components/modal/v2/styles/components/_content.scss
  src/components/modal/v2/styles/components/_donut.scss
  src/components/modal/v2/styles/components/_header.scss
  src/components/modal/v2/styles/components/_instructions.scss
  src/components/modal/v2/styles/components/_offer-card.scss
  src/components/modal/v2/styles/globals/_colors.scss
  src/components/modal/v2/styles/globals/_common.scss
  tests/functional/snapshots/US/DEV0000000EAZ/custom/-600-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_NO_INTEREST/mobile/99-Shows_correct_content_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_NO_INTEREST/mobile/99-Shows_correct_content_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_NO_INTEREST/mobile/99-Shows_correct_content_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_NO_INTEREST/mobile/99-Shows_correct_content_for_amount-mobile-snap.png
Labels: testing complete, approved

#1030 ci: update custom snaps
  tests/functional/snapshots/US/DEV0000000EAZ/custom/-600-snap.png
Labels: approved

#1031 chore: cut release
  tests/functional/snapshots/US/DEV0000000EAZ/custom/-600-snap.png
Labels: testing complete, approved

#1033 chore: cut release
  tests/functional/spec/US/custom/custom.test.js
Labels: testing complete, approved

#1034 refactor: update spacing for FR 1x1 flex banners
  src/server/locale/FR/mutations/gplq.js
  tests/functional/snapshots/FR/DEV00000FRPLQ/flex/color-black_ratio-1x1-1100-snap.png
  tests/functional/snapshots/FR/DEV00000FRPLQ/flex/color-blue_ratio-1x1-1100-snap.png
  tests/functional/snapshots/FR/DEV00000FRPLQ/flex/color-blue_ratio-1x1-400-snap.png
  tests/functional/snapshots/FR/DEV00000FRPLQ/flex/color-blue_ratio-1x4-400-snap.png
  tests/functional/snapshots/FR/DEV00000FRPLQ/flex/color-gray_ratio-1x1-1100-snap.png
  tests/functional/snapshots/FR/DEV00000FRPLQ/flex/color-white_ratio-1x1-1100-snap.png
Labels: testing complete, snapshots

#1037 feat: add v4Design flag to PL2GO modals
  content/modals/US/PL2GO/pl2go_long_term.json
  content/modals/US/PL2GO/pl2go_short_term.json
Labels: testing complete, approved

#1036 refactor: update hyperlink css
  src/components/modal/v2/parts/InlineLinks.jsx
  src/components/modal/v2/styles/components/_inline-links.scss
Labels: testing complete, approved
