Repository paypal/paypal-messaging-components, pull requests merged in 2023-05, with the labels that each got.

#929 refactor: add 0% TAEG to IT Pi3 messages and modals
  content/messages/IT/short_term_nq.json
  content/messages/IT/short_term_q.json
  content/modals/IT/short_term.json
  src/server/locale/IT/mutations/short_term_nq.js
  src/server/locale/IT/mutations/short_term_q.js
  src/server/locale/IT/styles/flex/base.css
  tests/functional/v2/testFn/multi.js
  tests/functional/v2/testFn/payIn1.js
  tests/functional/v2/testFn/shortTerm.js
  tests/functional/v2/utils/selectors.js
Labels: testing complete, approved

#932 feat: Add 0% TAE to ES Pi3 Modals (DTCRCMERC-2245)
  content/modals/ES/short_term.json
Labels: testing complete, approved, snapshots

#933 feat: Update Error States for US Pay Monthly and DE LT modals for Accessibility (DTCRCMERC-2260)
  src/components/modal/v2/parts/Icon.jsx
  src/components/modal/v2/styles/components/_calculator.scss
Labels: testing complete, approved, snapshots, Accessibility

#936 feat: Update UK Pi3 Legal Disclosure (DTCRCMERC-2267)
  content/modals/GB/short_term.json
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/desktop/0-Donuts_show_correct_periodic_payment_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/desktop/0-Shows_correct_subheadline_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/desktop/2000.01-Donuts_show_correct_periodic_payment_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/desktop/2000.01-Shows_correct_subheadline_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/desktop/30-Donuts_show_correct_periodic_payment_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/desktop/30-Shows_correct_subheadline_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/mobile/0-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/mobile/0-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/mobile/2000.01-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/mobile/2000.01-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/mobile/30-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/GB/DEV_GB_SHORT_TERM/mobile/30-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/GB/DEV_GB_SHORT_TERM/mobile/0-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/GB/DEV_GB_SHORT_TERM/mobile/0-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/GB/DEV_GB_SHORT_TERM/mobile/2000.01-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/GB/DEV_GB_SHORT_TERM/mobile/2000.01-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/GB/DEV_GB_SHORT_TERM/mobile/30-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/GB/DEV_GB_SHORT_TERM/mobile/30-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/GB/DEV_GB_SHORT_TERM/mobile/0-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/GB/DEV_GB_SHORT_TERM/mobile/0-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/GB/DEV_GB_SHORT_TERM/mobile/2000.01-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/GB/DEV_GB_SHORT_TERM/mobile/2000.01-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/GB/DEV_GB_SHORT_TERM/mobile/30-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/GB/DEV_GB_SHORT_TERM/mobile/30-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/desktop/0-Donuts_show_correct_periodic_payment_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/desktop/0-Shows_correct_subheadline_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/desktop/2000.01-Donuts_show_correct_periodic_payment_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/desktop/2000.01-Shows_correct_subheadline_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/desktop/30-Donuts_show_correct_periodic_payment_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/desktop/30-Shows_correct_subheadline_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/mobile/0-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/mobile/0-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/mobile/2000.01-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/mobile/2000.01-Shows_correct_subheadline_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/mobile/30-Donuts_show_correct_periodic_payment_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/GB/DEV_GB_SHORT_TERM/mobile/30-Shows_correct_subheadline_for_amount-mobile-snap.png
Labels: testing complete, approved

#906 feature/DTCRCMERC-2002-Disclosure-Removal-Nebraska
  content/modals/US/v2_long_term.json
  content/modals/US/v2_long_term_xo.json
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/0-Amounts_below_199_show_correct_below_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_MULTI/desktop/0-Amount_persists_between_views-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Checkout_CTA_button_shows_correct_content-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/0-Amounts_below_199_show_correct_below_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Displays_correct_APR_legal_disclaimer-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_headline_information-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Update_offers_via_calculator-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_MULTI/desktop/0-Amount_persists_between_views-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
Labels: testing complete, approved
