Repository paypal/paypal-messaging-components, pull requests merged in 2023-09, with the labels that each got.

#968 refactor: remove stage references
  README.md
  globals.js
  jest.config.js
  src/components/modal/lib/hooks/applyNow.js
  src/components/modal/v2/lib/hooks/applyNow.js
  src/utils/sdk.js
  tests/unit/spec/src/components/modal/lib/hooks/applyNow.test.js
  tests/unit/spec/src/utils/sdk.test.js
  tests/unit/utils/setup.js
  webpack.config.dev.js
Labels: testing complete, approved

#983 chore: updated DE disclosure
  content/modals/DE/long_term.json
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_LONG_TERM/desktop/0-Amounts_below_99_show_correct_below_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_LONG_TERM/desktop/5000.01-Amounts_above_5000_show_correct_above_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_LONG_TERM/desktop/99-Offer_accordion_show_correct_payment_breakdown_information_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_LONG_TERM/desktop/99-Offer_accordion_show_correct_payment_headline_information-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_LONG_TERM/desktop/99-Update_offers_via_calculator-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_LONG_TERM/mobile/0-Amounts_below_99_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_LONG_TERM/mobile/5000.01-Amounts_above_5000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_MULTI/desktop/0-Amount_persists_between_views-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/DE/DEV_DE_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/DE/DEV_DE_LONG_TERM/mobile/0-Amounts_below_99_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/DE/DEV_DE_LONG_TERM/mobile/5000.01-Amounts_above_5000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/DE/DEV_DE_LONG_TERM/mobile/0-Amounts_below_99_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/DE/DEV_DE_LONG_TERM/mobile/5000.01-Amounts_above_5000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/DE/DEV_DE_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_LONG_TERM/desktop/0-Amounts_below_99_show_correct_below_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_LONG_TERM/desktop/5000.01-Amounts_above_5000_show_correct_above_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_LONG_TERM/desktop/99-Offer_accordion_show_correct_payment_breakdown_information_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_LONG_TERM/desktop/99-Offer_accordion_show_correct_payment_headline_information-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_LONG_TERM/desktop/99-Update_offers_via_calculator-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_LONG_TERM/mobile/0-Amounts_below_99_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_LONG_TERM/mobile/5000.01-Amounts_above_5000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_MULTI/desktop/0-Amount_persists_between_views-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/DE/DEV_DE_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
Labels: testing complete, approved, snapshots

#982 feat: frites modals en variants
  content/modals/ES/short_term_en.json
  content/modals/FR/short_term_en.json
  content/modals/IT/short_term_en.json
  src/components/modal/v2/lib/utils.js
  src/library/controllers/modal/interface.js
  src/library/zoid/message/validation.js
  src/library/zoid/modal/component.js
Labels: testing complete, approved

#986 fix: components render inside external zoid iframes
  src/library/controllers/modal/setup.js
  src/library/zoid/message/component.js
  src/library/zoid/modal/component.js
  src/library/zoid/treatments/component.js
  src/utils/constants.js
  src/utils/sdk.js
  utils/devServerProxy/proxy.js
Labels: testing complete, approved

#989 chore: cut release
  .github/PULL_REQUEST_TEMPLATE.md
  src/library/controllers/modal/setup.js
  src/library/zoid/message/component.js
  src/library/zoid/modal/component.js
  src/library/zoid/treatments/component.js
  src/utils/constants.js
  src/utils/sdk.js
  utils/devServerProxy/proxy.js
Labels: testing complete, approved

#985 feat: updated input on calculator for better accessibility
  src/components/modal/v2/parts/Calculator.jsx
Labels: testing complete, approved

#980 feat: Screen reader /mo for messages and modals (DTCRCMERC-1941)
  content/messages/US/long_term_multi_eqz.json
  content/messages/US/long_term_multi_eqz_mixed.json
  content/messages/US/long_term_multi_gtz.json
  content/messages/US/long_term_single_eqz.json
  content/messages/US/long_term_single_eqz_mixed.json
  content/messages/US/long_term_single_gtz.json
  content/messages/US/ppc_ezp_multi_eqz.json
  content/messages/US/ppc_ezp_multi_gtz.json
  content/messages/US/ppc_ezp_single_eqz.json
  content/messages/US/ppc_ezp_single_gtz.json
  content/offers/US/v2_long_term.json
  src/components/modal/v2/parts/OfferCard.jsx
  src/server/locale/US/PAY_LATER_LONG_TERM/mutations/long_term_multi_gtz.js
  tests/functional/snapshots/US/DEV0000000PMG/text/text.align-center-600-snap.png
  tests/functional/snapshots/US/DEV0000000PMZ/text/text.align-center-600-snap.png
  tests/functional/snapshots/US/DEV0000000PSG/text/text.align-center-600-snap.png
  tests/functional/snapshots/US/DEV0000000PSZ/text/text.align-center-600-snap.png
  tests/functional/snapshots/US/DEV00USLTMQGZ/text/logo.type-alternative_text.size-10-600-snap.png
  tests/functional/snapshots/US/DEV00USLTSQEZ/text/logo.type-none-600-snap.png
  tests/functional/snapshots/US/DEV00USLTSQEZ/text/logo.type-none_text.color-grayscale-600-snap.png
  tests/functional/snapshots/US/DEV00USLTSQEZ/text/logo.type-none_text.color-monochrome-600-snap.png
  tests/functional/snapshots/US/DEV00USLTSQEZ/text/logo.type-none_text.color-white-600-snap.png
  tests/functional/snapshots/US/DEV00USLTSQEZ/text/text.align-right-600-snap.png
  tests/functional/v2/testFn/longTerm.js
Labels: testing complete, approved, snapshots, Accessibility
