Repository paypal/paypal-messaging-components, pull requests merged in 2024-03, with the labels that each got.

#1054 feat: update pm legal disclaimer and disclosure
  content/modals/US/PL2GO/pl2go_long_term.json
  content/modals/US/PLHub/plhub_long_term.json
  content/modals/US/v2_long_term.json
  content/modals/US/v2_long_term_xo.json
  content/offers/US/v2_long_term.json
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/0-Amounts_below_199_show_correct_below_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/199-Displays_correct_APR_legal_disclaimer-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_headline_information-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/199-Update_offers_via_calculator-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_MULTI/desktop/0-Amount_persists_between_views-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Checkout_CTA_button_shows_correct_content-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_PL2GO/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_PL2GO/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_PL2GO/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_PL2GO/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/0-Amounts_below_199_show_correct_below_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Displays_correct_APR_legal_disclaimer-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_headline_information-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Update_offers_via_calculator-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_MULTI/desktop/0-Amount_persists_between_views-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
Labels: testing complete, approved

#1050 feat: Logic to handle merchant including placement and page-type parameters the SDK (DTCRCMERC-2883)
  src/library/controllers/message/interface.js
  src/library/controllers/message/setup.js
  src/library/zoid/message/component.js
  src/library/zoid/message/validation.js
  tests/unit/spec/src/zoid/message/validation.test.js
Labels: testing complete, downstream dependency, approved

#1059 chore: cut release
  src/library/controllers/message/interface.js
  src/library/controllers/message/setup.js
  src/library/zoid/message/component.js
  src/library/zoid/message/validation.js
  tests/unit/spec/src/zoid/message/validation.test.js
Labels: testing complete, approved

#1062 feat: fix preapproval pi4 xo modal
  content/modals/US/v2_short_term_xo.json
  src/components/modal/v2/parts/BodyContent.jsx
  src/components/modal/v2/parts/CheckoutHeader.jsx
Labels: testing complete, approved

#1063 chore: cut release
  content/modals/US/v2_short_term_xo.json
  src/components/modal/v2/parts/BodyContent.jsx
  src/components/modal/v2/parts/CheckoutHeader.jsx
Labels: approved

#1058 fix: setup global state from script in modal setup
  src/library/controllers/message/setup.js
  src/library/controllers/modal/setup.js
  src/library/messaging.js
  src/library/modal.js
  src/utils/global.js
  tests/unit/spec/src/controllers/message/setup.test.js
  tests/unit/utils/insertMockScript.js
Labels: testing complete, approved

#1060 fix: de header margin
  src/components/modal/v2/styles/components/_header.scss
Labels: testing complete, approved

#1064 refactor: updates QL checkout modal close button styles
  src/components/modal/v2/styles/components/_header.scss
  src/library/zoid/modal/prerenderTemplate.jsx
Labels: testing complete, approved

#1065 feat: improve ql xo ax
  content/modals/US/v2_long_term_xo.json
  content/modals/US/v2_short_term_xo.json
  content/offers/US/v2_long-term_checkout.json
  src/components/modal/v2/parts/Icon.jsx
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Checkout_CTA_button_shows_correct_content-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/testFn/longTerm.js
  utils/devServerProxy/config/US/index.js
Labels: testing complete, approved

#1067 chore: cut release
  content/modals/US/v2_long_term_xo.json
  content/modals/US/v2_short_term_xo.json
  content/offers/US/v2_long-term_checkout.json
  src/components/modal/v2/parts/Icon.jsx
  src/components/modal/v2/styles/components/_header.scss
  src/library/controllers/message/setup.js
  src/library/controllers/modal/setup.js
  src/library/messaging.js
  src/library/modal.js
  src/library/zoid/modal/prerenderTemplate.jsx
  src/utils/global.js
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Checkout_CTA_button_shows_correct_content-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/testFn/longTerm.js
  tests/unit/spec/src/controllers/message/setup.test.js
  tests/unit/utils/insertMockScript.js
  utils/devServerProxy/config/US/index.js
Labels: approved
