Repository paypal/paypal-messaging-components, pull requests merged in 2024-11, with the labels that each got.

#1152 refactor: update us pm modal disclosure
  content/modals/US/PL2GO/pl2go_long_term.json
  content/modals/US/PLHub/plhub_long_term.json
  content/modals/US/v2_long_term.json
  content/modals/US/v2_long_term_xo.json
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/0-Amounts_below_199_show_correct_below_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/199-Displays_correct_APR_legal_disclaimer-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_headline_information-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/199-Update_offers_via_calculator-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/desktop/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_MULTI/desktop/0-Amount_persists_between_views-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Checkout_CTA_button_shows_correct_content-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_CHECKOUT/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_PL2GO/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_PL2GO/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_PL2GO/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_LONG_TERM_PL2GO/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/0-Amounts_below_199_show_correct_below_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Displays_correct_APR_legal_disclaimer-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Offer_cards_show_correct_payment_headline_information-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/199-Update_offers_via_calculator-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/desktop/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/0-Amounts_below_199_show_correct_below_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Displays_correct_APR_legal_disclaimer-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_breakdown_information_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Offer_cards_show_correct_payment_headline_information-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/199-Update_offers_via_calculator-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_LONG_TERM/mobile/20000.01-Amounts_above_20000_show_correct_above_threshold_warning-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_MULTI/desktop/0-Amount_persists_between_views-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_MULTI/mobile/0-Amount_persists_between_views-mobile-snap.png
Labels: testing complete, approved, snapshots

#1154 refactor: update au disclosure
  content/modals/AU/short_term.json
Labels: testing complete, approved

#1157 refactor: update request to accept raw JSON or encoded
  src/components/message/Message.js
  tests/unit/spec/src/components/message/Message.test.js
  utils/devServerProxy/lib/miscellaneous.js
  utils/devServerProxy/messages.js
  utils/devServerProxy/modals.js
Labels: testing complete, approved

#1158 ci: update playwright automated tests to run on all PRs
  .github/workflows/playwright.yml
Labels: testing complete, approved, Accessibility
