Repository paypal/paypal-messaging-components, pull requests merged in 2024-10, with the labels that each got.

#1136 feat: Condense Automated Scan Tests (DTCRCMERC-3574)
  .github/workflows/playwright.yml
  tests/playwright/tests/sdk/modals/longTerm.spec.js
  tests/playwright/tests/sdk/modals/multi.spec.js
  tests/playwright/tests/sdk/modals/shortTerm.spec.js
Labels: Accessibility

#1138 refactor: Condense Messages to a Few for Accessibility Automated Testing
  .github/workflows/playwright.yml
  tests/playwright/pages/messages_fixture.js
  tests/playwright/tests/sdk/messages/longTerm.spec.js
  tests/playwright/tests/sdk/messages/multi.spec.js
  tests/playwright/tests/sdk/messages/shortTerm.spec.js
Labels: Accessibility

#1139 feat: add new content to support new channel
  content/modals/US/long_term_df.json
  content/offers/US/long_term_df.json
  src/components/modal/v2/parts/Calculator.jsx
  src/components/modal/v2/parts/Header.jsx
  src/components/modal/v2/parts/Icon.jsx
  src/components/modal/v2/parts/Instructions.jsx
  src/components/modal/v2/styles/components/_instructions.scss
  utils/devServerProxy/config/US/index.js
Labels: testing complete, approved

#1135 refactor: update apr and content
  content/modals/US/legacy_ppc_ezp.json
  content/modals/US/legacy_ppc_ni.json
  content/modals/US/v2_ppc_ni.json
  tests/functional/v2/snapshots/modal/api/US/DEV_US_NO_INTEREST/desktop/99-Shows_correct_content_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/api/US/DEV_US_NO_INTEREST/mobile/99-Shows_correct_content_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/sdk/US/DEV_US_NO_INTEREST/mobile/99-Shows_correct_content_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/standalone/US/DEV_US_NO_INTEREST/mobile/99-Shows_correct_content_for_amount-mobile-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_NO_INTEREST/desktop/99-Shows_correct_content_for_amount-desktop-snap.png
  tests/functional/v2/snapshots/modal/webpage/US/DEV_US_NO_INTEREST/mobile/99-Shows_correct_content_for_amount-mobile-snap.png
Labels: testing complete, approved

#1149 feat: Flex-Test Accessibility Automation & Run Tests Only In chrome (DTCRCMERC-3553)
  demo/accessibility/flexsdk.html
  playwright.config.js
  tests/playwright/tests/sdk/messages/multi.spec.js
Labels: approved, Accessibility

#1140 Playwright Automated Testing (DTCRCMERC-3574)
  .github/workflows/playwright.yml
  .gitignore
  demo/accessibility/colorsdk.html
  demo/accessibility/flexsdk.html
  package.json
  playwright.config.js
  src/components/modal/v2/parts/Calculator.jsx
  src/components/modal/v2/styles/components/_calculator.scss
  tests/playwright/README.md
  tests/playwright/pages/base.js
  tests/playwright/pages/messages_fixture.js
  tests/playwright/pages/modals_fixture.js
  tests/playwright/tests/sdk/messages/multi.spec.js
  tests/playwright/tests/sdk/modals/multi.spec.js
  tests/playwright/util/selectors.js
Labels: testing complete, approved, Accessibility
